export interface IProduct {
  rateAvg:number,
  rateCount:number,
  id: number,
  title: string,
  slug: string,
  description: string,
  imgCover: string,
  images: string[],
  price: number,
  priceAfterDiscount: number,
  quantity: number,
  category:string,
  isSuperAdmin:boolean,
  sold: number,
}
